### ISSUE TITLE
Should XmlEntities.encodeNonUTF also replace "&" with "&amp;"?

### ISSUE THREAD

**Issue by cearny** [mdevils/html-entities#14]
It seems it's doing it "behind my back". I am already encoding the illegal XML characters myself and wanted to just make sure we don't end up with non-UTF characters. & seems pretty UTF to me :smile:

**Comment by mdevils** [comment]
Hello @cearny. Sorry for a delay in the response. `&` character is part of the ASCII range (below char code 256), therefore it is not UTF.
