### ISSUE TITLE
HTML chars without ending ; still decoded

### ISSUE THREAD

**Issue by jkrenge** [mdevils/html-entities#19]
The `.decode()` function is too aggressive as it decodes even incomplete HTML characters like in this example:

```javascript
var url = 'http://some-url.de/?param1=value1&lang=en';
console.log(require('html-entities').AllHtmlEntities.decode(url));
```

yields

```bash
http://some-url.de/?param1=value1⟨=en
```

This means, `&lang` (probably a not so rare URL parameter) is decoded as if it was `&lang;`, the character `⟨`.

**Comment by dularion** [comment]
Same issue for us, also with a url

**Comment by mdevils** [comment]
`scope` option was added to `decode()`.
