### ISSUE TITLE
At html4-entities, yuml is repeated twice instead of distinguish between yuml and Yuml

### ISSUE THREAD

**Issue by hwangar** [mdevils/html-entities#20]
Same happens with dagger

**Comment by hwangar** [comment]
... and same with all uppercase greek letters
(sorry for being a PITA :P)

**Comment by mdevils** [comment]
Hello @hwangar, can you please provide a short code demonstrating the problem?

**Comment by hwangar** [comment]
Of course:
`
var Entities = require('html-entities'). Html4Entities;
var entities = new Entities();

var raw='Ÿ†‡ ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ';
assert.equal(entities.decode(entities.encodeNonUTF(raw)), raw);
`

**Comment by hwangar** [comment]
&prime; is duplicated too

**Comment by hwangar** [comment]
I fixed the file as I found typos, do you want me to attach the fixed html4 js?

**Comment by dan1wang** [comment]
fixed on 2017-04-01 by Karman Kertesz. Please close this issue.
