### ISSUE TITLE
360 anti-virus warns this is virus.

### ISSUE THREAD

**Issue by charlesgao** [mdevils/html-entities#28]
360 anti-virus warns this is virus.
Type
virus.js.qexvmc.1070

\frontend\node_modules\html-entities\lib\html5-entities.js

MD5:
e23b7edbddd7c994e4c67e9bdf97c4aa

**Comment by Trackhe** [comment]
Here is the solution https://www.360totalsecurity.com/de/support/how-to/uninstall/
