### ISSUE TITLE
Possible optimization

### ISSUE THREAD

**Issue by maartenschumacher** [mdevils/html-entities#30]
https://github.com/mdevils/node-html-entities/blob/dc08bde42ee6468d60ca617061b0b37b2edc45ca/lib/html5-entities.js#L166

Couldn't you put the output of this in a JSON file? As far as I can see this information is static, so shouldn't have to be calculated each time.

If you think it's a good idea I can get a PR together.

**Comment by mdevils** [comment]
Hello @maartenschumacher. Sorry for a delay in the response.
Good idea, I'll try implementing it.

**Comment by mdevils** [comment]
This optimisation was now applied.
