### ISSUE TITLE
CodePoints encoding and supplementary plane support

### ISSUE THREAD

**Issue by ainthek** [mdevils/html-entities#33]
IMHO cow shell be encoded as &#128004;
however it is not, is this supported ? If my assumption is wrong please correct me. 

see test case
$ node html/html-encode
[ '🐄', '🐄', '🐄' ]
[ '🐄', '🐄', '🐄' ]
[ '&#55357;&#56324;', '&#55357;&#56324;', '&#55357;&#56324;' ]
[ '&#55357;&#56324;', '&#55357;&#56324;', '&#55357;&#56324;' ]
Assertion failed

var entities = new(require('html-entities').AllHtmlEntities)();
let cows=[
	"🐄",
	"\u{1f404}",
	"\uD83D\uDC04"];

console.log(cows);
console.log(cows.map((c)=>entities.encode(c)));
console.log(cows.map((c)=>entities.encodeNonASCII(c)));
console.log(cows.map((c)=>entities.encodeNonUTF(c)));

console.assert(entities.encodeNonUTF(cows[1])==="&#128004;")

http://www.amp-what.com/unicode/search/cow

**Comment by mdevils** [comment]
I believe this is fixed now.
