### ISSUE TITLE
' is not correctly decoded 

### ISSUE THREAD

**Issue by hugoblanc** [mdevils/html-entities#40]
Almost every character are sucessfully decoded but &rsquo; => ' is still not decoded

You can confirm on this page [decode online](https://codebeautify.org/html-decode-string)
that &rsquo; is equivalent to '

**Comment by mdevils** [comment]
Hello @hugoblanc. Sorry for a delay in the response. Can you please use triple backtick and paste the text which is improperly decoded? Because I could not understand it from your message.

**Comment by hugoblanc** [comment]
To be honest I don't remember. I'm closing it
