### ISSUE TITLE
There is any breaking change from in new 2.x.x version?

### ISSUE THREAD

**Issue by RodrigoTomeES** [mdevils/html-entities#47]
Hi,

I've been looking through the repository but haven't found any information about it. Is it safe to upgrade from v.1.4.0 to the new version?

**Comment by elishaterada** [comment]
There was a breaking change of handling undefined and null values, which I made a PR for and that was the only thing I noticed. You should try upgrading it and see if your use case might be impacted.

https://github.com/mdevils/html-entities/pull/46

**Comment by mdevils** [comment]
Hello, that's a fair point.

Here is the changelog: https://github.com/mdevils/html-entities/blob/master/CHANGELOG.md
