### ISSUE TITLE
Not terminated entities not supported

### ISSUE THREAD

**Issue by fb55** [mdevils/html-entities#50]
Hi 👋 ! I am currently trying to get a better understanding of the differences in the benchmarks between HTML entity libraries. I found a bug in `html-entities` along the way, hope this is useful:

Entities that are part of a string are currently not supported. Eg. `&uumlber` should be decoded as `über`. `html-entities` currently leaves it unchanged.

**Comment by mdevils** [comment]
Hello @fb55, thank you so much for this discovery. The bug is fixed in `2.0.5`.
