### ISSUE TITLE
Module '"html-entities"' has no exported member 'encode'.

### ISSUE THREAD

**Issue by flowck** [mdevils/html-entities#53]
Hi, I was following the docs and encountered the following error while importing `encode` from `html-entities`: 

`Module '"html-entities"' has no exported member 'encode'.`

![Screenshot 2021-03-05 at 22 42 32](https://user-images.githubusercontent.com/1679333/110181805-2b846d00-7e04-11eb-961c-0ae6165e73cc.png)

After exploring the definition file `index.d.ts` from `html-entities` I found out that nor `encode`, and `decode` are exported directly. 

![Screenshot 2021-03-05 at 22 44 48](https://user-images.githubusercontent.com/1679333/110182279-68506400-7e04-11eb-8ed5-7e1712963b11.png)

Importing `Html5Entities` works:

![Screenshot 2021-03-05 at 22 42 44](https://user-images.githubusercontent.com/1679333/110181817-2c1d0380-7e04-11eb-8a9c-93ed40b9c8ac.png)

Are the docs outdated?

Kind regards,
Firmino

**Comment by mdevils** [comment]
Hello @flowck,

It seems that you are following docs of the latest version while you have an old version installed locally.

Update `html-entities` and you'll get the new API.

**Comment by flowck** [comment]
Sorry about that mate.

It turns out `webpack` is using `html-entities@1.4.1`. 

Thank you.
