### ISSUE TITLE
converting `&nbsp;` fails jest test

### ISSUE THREAD

**Issue by dnsmob** [mdevils/html-entities#58]
surprisingly, this conversion fails. not sure why, it looks quite fine to me. 🤔 could it be the ascii character itself?

`expect(decode('first&nbsp;second')).toEqual('first second')`

the equality looks suspicious though, but that's the log on terminal
```
    Expected: "first second"
    Received: "first second"
```

macOS 10.15.7, html-entities 2.3.2, ts-jest 25.2.1

**Comment by mdevils** [comment]
Hello,

Aside from just a space, there is also a non-breaking space in unicode :) &nbsp; means "Non-Breaking SPace"

https://www.compart.com/en/unicode/U+00A0

**Comment by dnsmob** [comment]
fock me. i never ever noticed that nbsp stood for the non breaking space!!!!! 🤣
