### ISSUE TITLE
Not decoding &eacute;

### ISSUE THREAD

**Issue by emmtte** [mdevils/html-entities#62]
with `import {decode} from 'html-entities'`
`decode` not decode `&eacute;` (é)
the complete string is `&amp;eacute;`
Is possible to fix that

Thanks

**Comment by mdevils** [comment]
Hello @emmtte,

I've just tried this and it worked:

```js
const {decode} = require('./lib');
console.log(decode('&eacute;')); // é
```

Could you please clarify what exactly doesn't work in your case?

**Comment by emmtte** [comment]
Hi @mdevils, thanks for answer.
The complete string is ```&amp;eacute;``` who is not correctly decoded

**Comment by mdevils** [comment]
Hello @emmtte,

The correct decoding of `&amp;eacute;` is `&eacute;`. `&amp;` translates to `&`.
