### ISSUE TITLE
html-entities doesn't decode html breaks '<br />'

### ISSUE THREAD

**Issue by jrhager84** [mdevils/html-entities#63]
Is there a way to add a custom carriage return for breaks? I'm not sure why, but the self-closed break isn't decoding. Is there a setting for this? I've checked the docs and don't have any answers. Thanks!

**Comment by mdevils** [comment]
Hello @jrhager84. I didn't understand your question. Could you please describe the problem in the following way:

1. What you are trying to do (the code)
2. What is the expected result
3. What is the actual result

**Comment by jrhager84** [comment]
> Hello @jrhager84. I didn't understand your question. Could you please describe the problem in the following way:
> 
> 1. What you are trying to do (the code)
> 2. What is the expected result
> 3. What is the actual result

A break is an html element that indicates a new line, so I guess I imagined it would add a `\n`.

I expect a new line. I get no new line. I had to add my own implementation to capture the breaks.

I'll add the code when I'm not on my phone, but it really is as simple as the <br/> tags aren't being turned into new lines.

**Comment by mdevils** [comment]
Hello @jrhager84,

Right, `<br />` is an html element. This library doesn't deal with html elements, it only encodes / decodes HTML entities.

More info can be found here: https://dev.w3.org/html5/html-author/charref

**Comment by jrhager84** [comment]
> Hello @jrhager84,
> 
> Right, `<br />` is an html element. This library doesn't deal with html elements, it only encodes / decodes HTML entities.
> 
> More info can be found here: https://dev.w3.org/html5/html-author/charref

Seems like quite an oversight, but I suppose my solution will work. Just seems odd that it wouldn't handle breaks. 🤷‍♂️
