### ISSUE TITLE
encode function encodes 0 to empty string

### ISSUE THREAD

**Issue by meytin1337** [mdevils/html-entities#64]
Code to reproduce: 
```
import { encode } from 'html-entities'
console.log(encode(0))
```
running
```
import { encode } from 'html-entities'
console.log(typeof(encode(0))
```
gives console output `string`
running 
```
import { encode } from 'html-entities'
console.log(encode(0).length)
```
gives console output `0`

**Comment by guptadeepanshu21** [comment]
Are you able to import 'encode' directly from 'html-entities'.
I am getting following error :

export 'encode' (imported as 'encode') was not found in 'html-entities'

**Comment by mdevils** [comment]
Hello @meytin1337, `encode` accepts one of 3 types: `string | undefined | null`, not `number`. Escaping numbers is not needed, none of numbers have any characters to escape.

**Comment by mdevils** [comment]
Hello @guptadeepanshu21.

What version are you using? Can you also paste your code?

**Comment by guptadeepanshu21** [comment]
Webpack-dev-server is using html-entities as a dependency.

in webpack-dev-server, there is a file called overlay.js in which following piece of code is written:

import { encode } from 'html-entities'

when we build our project we get an error "export 'encode' (imported as 'encode') was not found in 'html-entities'"

When I tried to import it like import { Html4Entities } from 'html-entities' and used Html4Entities.encode, the error didn't occur.


and also I tried to use html-entities in my local JS project.
In VS code, when we try import encode, intellisense doesn't show it as a suggestion but it shows as 'Html4Entities' .

Can you try to do the same ?

**Comment by mdevils** [comment]
@guptadeepanshu21 

> When I tried to import it like import { Html4Entities } from 'html-entities' and used Html4Entities.encode, the error didn't occur.

It means you have an older version of html-entities installed for some reason. Latest `webpack-dev-server` uses the latest version of `html-entities`: https://github.com/webpack/webpack-dev-server/blob/master/package.json#L53

**Comment by guptadeepanshu21** [comment]
@mdevils  Please check this. I installed the latest version just now.

![image](https://user-images.githubusercontent.com/50165416/155038223-b302ea2b-60d9-4623-b29b-f7b68a698cc9.png)

**Comment by mdevils** [comment]
@guptadeepanshu21  Try writing

```
console.log(require('html-entities/package.json').version);
```

to know what exact version you have installed right now.

**Comment by guptadeepanshu21** [comment]
@mdevils you are correct, somehow webpack-dev-server is not getting the latest version. I will try to debug it.
Anyway, Thank you for helping.
