### ISSUE TITLE
How to migrate from v1.x to v2.x

### ISSUE THREAD

**Issue by WebmasterClickPanda** [mdevils/html-entities#67]
Hi!

I just updated the package but now Im getting the error "Entities is not a constructor".

In the version 1.x, the readMe said to declare the funcion like this:

`const entities = new Entities();`

But now in the newest version that constructor i not available, how can I upgrade the package? thanks!

**Comment by mdevils** [comment]
Hello @WebmasterClickPanda,

Please checkout CHANGELOG, the whole upgrade process is described there: https://github.com/mdevils/html-entities/blob/master/CHANGELOG.md#200
