### ISSUE TITLE
The "timesbar" entity is not decoded correctly

### ISSUE THREAD

**Issue by molund** [mdevils/html-entities#77]
There is a decoding bug that impacts the ⨱ (timesbar) entity 

We have the following string
```
Kun&timesbar;alas Heritage Site/Conservancy
```
It should be decoded as "Kun⨱alas Heritage Site/Conservancy" but instead it gets decoded as "Kun×bar;alas Heritage Site/Conservancy"

**Comment by mdevils** [comment]
Hello @molund. Sorry for a huge delay in the response.

Thank you for your bug report. This bug was fixed in version 2.3.4.
