### ISSUE TITLE
Decoding entities from a state component - react native

### ISSUE THREAD

**Issue by rashonwill** [mdevils/html-entities#80]
I'm saving values within a react native state component and mapping through to return the value to the ui, but the values I wish to decode are not being decoded. Is there an example on how this works within react native?
 const [freeMedia, setFreeMedia] = useState();

{freeMedia && freeMedia.length > 0
              ? freeMedia.map((uploads) => {
            return(
<>
                        <Text
                            numberOfLines={2}
                            ellipsizeMode="tail"
                            style={styles.cardTextTitle}
                          >
                            {decode(uploads.videotitle)}
                          </Text>
</>
)
})
 : null}

**Comment by mdevils** [comment]
Hello @rashonwill, I'm not sure ReactNative can do what you need. Pasting raw HTML doesn't work in ReactNative.
