### ISSUE TITLE
Confusion b/t ~ (Tilde) and ˜ (Small Tilde or Overline)

### ISSUE THREAD

**Issue by Abrham007** [mdevils/html-entities#96]
It seems that it is interchanging or switching the Tilde and the Small Tilde html entity's should be an easy fix

**Comment by mdevils** [comment]
Hello @Abrham007. I did not understand the issue you're talking about. Could you please be more specific? What exact problem are you experiencing?

**Comment by Abrham007** [comment]
Hello @mdevils I can't seem to reproduce it anymore. It some how resolved it self I will close this issue now.
